### ISSUE TITLE
Way to get listings by agent?

### ISSUE THREAD

**Issue by advaitsaravade** [Froren/realtorca#1]
I was wondering if the node app could search for listings on realtor.ca by REALTOR name/MLS identifier? (sorry I had to open this as an issue, there was no way to contact you on github) :/

**Comment by kristophor** [comment]
there definitely is one，but I am in China right now, will get back to you Monday or Tuesday 


发自 iPhone 版 Yahoo 邮箱


星期四, 九月 28, 2017, 10:02 于 Advait Saravade <notifications@github.com>写道：


I was wondering if the node app could search for listings on realtor.ca by REALTOR name/MLS identifier? (sorry I had to open this as an issue, there was no way to contact you on github) :/

**Comment by Froren** [comment]
Hey hmm I hadn't really checked it out. It seems like you can, with the `OrganizationId` parameter. 

(You can find it from a broker page like so: https://www.realtor.ca/Residential/OfficeDetails.aspx?OrganizationId=50357)

**Comment by kristophor** [comment]
correct， you can also search by agent ID

发自 iPhone 版 Yahoo 邮箱


星期四, 九月 28, 2017, 11:25 于 Froren <notifications@github.com>写道：


Hey hmm I hadn't really checked it out. It seems like you can, with the OrganizationId parameter.

(You can find it from a broker page like so: https://www.realtor.ca/Residential/OfficeDetails.aspx?OrganizationId=50357)

**Comment by advaitsaravade** [comment]
@kristophor @Froren thanks for guiding me in the right direction. You can search using agent ID (it can actually be called via the opts variable using IndividualID rather than AgentID) and its value can be obtained from the agent's URL on realtorca.
