### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by abidiare** [Froren/realtorca#11]
hey I am trying to get all listings from toronto and vancover. I am very new at python can you help?

**Comment by t1nfoil** [comment]
I have some go source to do just that, not sure if this is what you're after but check out https://github.com/80at8/mls

todo - pagination support

**Comment by Froren** [comment]
hey @abidiare, sounds like a neat project. 

Do you know how to make an HTTP request in python? You can read here for more information if not: https://realpython.com/python-requests/#the-get-request

To get information from realtor.ca, you need to make a `POST` request to `https://api2.realtor.ca/Listing.svc/PropertySearch_Post`, with your search query in the `data` parameter. So for instance if you want to get a very basic query, you can use the following snippet:

```
import requests
response = requests.post('https://api2.realtor.ca/Listing.svc/PropertySearch_Post', data={
  'CultureId': 1,
  'ApplicationId': 1,
  'PropertySearchTypeId': 1
})

print(response.json())
```

`response.json()` should show you data that you can access in your program. 

From here, you can add things to the `data` map in the request. If you look at the README, you can find different kinds of fields you can input to get different results and specify how you want to search for properties: https://github.com/Froren/realtorca#api-referenceoptions

For instance, if you use 
```
data={
  'CultureId': 1,
  'ApplicationId': 1,
  'PropertySearchTypeId': 1,
  'PriceMin': 2000000,
  'PriceMax': 2000000
}
```
Your output will only show properties that will cost 2 million dollars.

Hope this helps! Let us know if you get stuck.

**Comment by Froren** [comment]
I'm going to close this out for inactivity, but happy to reopen the discussion whenever.
