### ISSUE TITLE
realtorapi return 404 

### ISSUE THREAD

**Issue by ManinderQservices** [Froren/realtorca#25]
using this api https://api.realtor.ca/Listing.svc/PropertySearch_Post return not found

**Comment by stuartathompson** [comment]
Same for me. Did they add new security features? Going to [the URL directly](https://api2.realtor.ca/Listing.svc/PropertySearch_Post?CultureId=1&ApplicationId=1&PropertySearchTypeId=1&LatitudeMax=45.680081&LongitudeMax=-73.361943&LongitudeMin=-74.068792&LatitudeMin=45.335813) causes this:

> Access Denied
> Error 15
> api2.realtor.ca
> 2021-02-05 20:25:16 UTC
> Why am I seeing this page?
> We display this page for you to verify that you are an actual human and not a robot.
> What should I do?
> Just click the I'm not a robot checkbox to pass the security check.
> What happened?
> This request was blocked by the security rules
> Your IP: 45.56.183.215
> Proxy IP: 45.223.18.18 (ID 101343-100)
> Incident ID: 1343000110395801728-1024565075614040782

**Comment by ap55** [comment]
+1. I am seeing the same error

**Comment by ManinderQservices** [comment]
> +1. I am seeing the same error

please check your request and baseurl both are correct then sort this issues

using like this =>
  const options = {
                url: baseURL + 'RealtorAPI',
                headers: {
                    "content-type": "application/json"
                },
                body: {
                    mlsNo: mlsNo,
                    url: url
                },
                json: true
            };



      request.post(options, function (propError, propResponse, propData) {

})

**Comment by ap55** [comment]
You were able to get the post api to return a response with listing data?

**Comment by ManinderQservices** [comment]
> You were able to get the post api to return a response with listing data?

yes post api return a json data

**Comment by ap55** [comment]
> > You were able to get the post api to return a response with listing data?
> 
> yes post api return a json data

Thanks for the update. Then the problems probably in my code.

**Comment by Froren** [comment]
Thanks for looping back @ManinderQservices, I'm glad you were able to get a resolution. Sounds like we can close this issue but I'm happy to help with any other issues that come up.
