### ISSUE TITLE
Is this still working?

### ISSUE THREAD

**Issue by DreamteamOne** [Froren/realtorca#6]
I am getting the following error code:

    [ErrorCode] => Array
        (
            [Id] => 400
            [Description] => The request was invalid.
            [LogId] => 
            [ProductName] => ! Push to A1-PR - Realtor API^16118
            [Version] => 1.0.6695.26582
        )

**Comment by Froren** [comment]
Hey @DreamteamOne. The package is still working for me. May I take a look at the source that's giving you that error?

**Comment by Froren** [comment]
Going to close this. But feel free to re-open if you're still having issues. I'm also still very curious to see what gave you that error.

**Comment by t1nfoil** [comment]
I am also having issues, I refactored the code (somewhat) into Go and attempted to post the form using nothing but the Min/Max Lat/Longs and Prices like in your example code, I too am getting a 400 error.

Code is here: https://github.com/80at8/mls/blob/master/mls_query.go

POST URL is:  https://api2.realtor.ca/Listing.svc/PropertySearch_Post
POST Form is:  LatitudeMax=&LatitudeMin=50.7661947&LongitudeMax=-113.1296838&LongitudeMin=-115.0120080&PriceMax=250000&PriceMin=200000

I receive the following:

`Response Status:
 200 OK

Response Headers:
 map[Vary:[Accept-Encoding Accept-Encoding] Access-Control-Allow-Origin:[*] X-Aspnet-Version:[4.0.30319] Content-Type:[application/json; charset=utf-8] Date:[Fri, 22 Mar 2019 02:57:11 GMT] Connection:[keep-alive] Cache-Control:[private] X-Powered-By:[ASP.NET] Arr-Disable-Session-Affinity:[true] Server:[nginx] Request-Context:[appId=cid-v1:bfc3c1b2-9e1b-437e-9616-7d1636843cb5] Access-Control-Expose-Headers:[Request-Context] Set-Cookie:[ASP.NET_SessionId=o31j4mjm1d4b1vgqlow22o0r; path=/; HttpOnly]]
{"ErrorCode":{"Id":400,"Description":"The request was invalid. (hidden)","LogId":"","ProductName":"! Push to Stage - Realtor API (Maintenance)^21389 [Wednesday, February 27, 2019 9:48:17 AM]","Version":"1.0.6997.17665"},"Paging":{"RecordsPerPage":0,"CurrentPage":0,"TotalRecords":0,"MaxRecords":0,"TotalPages":0,"RecordsShowing":0,"Pins":0},"Results":[],"Pins":[]}`

Not sure what I'm doing wrong.. does it still work with Node?

**Comment by Froren** [comment]
You need a `Culture`, `ApplicationId`, and `PropertySearchTypeId` value, try it again with those. I do notice that your go code provides the values as I expect.

The wrapper provides defaults for it: https://github.com/Froren/realtorca/blob/master/realtorca.js#L12

**Comment by t1nfoil** [comment]
Thank you! I added the missing fields (it turns out I had a variable typo Culture vs CultureId) and it worked right away!!

**Comment by Froren** [comment]
Oof, the README says `Culture` but it should be `CultureId`, thanks for bringing that to my attention.
