### ISSUE TITLE
How do you get access to the CREA Realtors API?

### ISSUE THREAD

**Issue by Tigatok** [Froren/realtorca#8]
Hi there,

I am just wondering how you got your api access to the CREA realtors api? I've sent them a few emails, but nothing has come back.

Thanks

**Comment by Froren** [comment]
Hey there,

I didn't get any privileged access either, this API just contains the public endpoints that realtor.ca surfaces when you do a search as an anonymous user. 

There was a thread a while back that went deeper into the topic: https://github.com/Froren/realtorca/issues/4

Good times.
